/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContentIndexRouteImport } from './routes/content/index'
import { Route as ContentNavigationRouteRouteImport } from './routes/content/navigation/route'
import { Route as ContentDataLoadersIndexRouteImport } from './routes/content/data-loaders/index'
import { Route as ContentDynamicRoutingIndexRouteImport } from './routes/content/dynamic-routing/index'
import { Route as ContentDynamicRoutingUserIdRouteImport } from './routes/content/dynamic-routing/$userId'
import { Route as ContentLayoutRoutesIndexRouteImport } from './routes/content/layout-routes/index'
import { Route as ContentNavigationIndexRouteImport } from './routes/content/navigation/index'
import { Route as ContentNavigationLinkRouteImport } from './routes/content/navigation/link'
import { Route as ContentNavigationUseNavigateRouteImport } from './routes/content/navigation/use-navigate'
import { Route as ContentNestedRoutingIndexRouteImport } from './routes/content/nested-routing/index'
import { Route as ContentRoutingIndexRouteImport } from './routes/content/routing/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentIndexRoute = ContentIndexRouteImport.update({
  id: '/content/',
  path: '/content/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentNavigationRouteRoute = ContentNavigationRouteRouteImport.update({
  id: '/content/navigation',
  path: '/content/navigation',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentDataLoadersIndexRoute = ContentDataLoadersIndexRouteImport.update({
  id: '/content/data-loaders/',
  path: '/content/data-loaders/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentDynamicRoutingIndexRoute =
  ContentDynamicRoutingIndexRouteImport.update({
    id: '/content/dynamic-routing/',
    path: '/content/dynamic-routing/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ContentDynamicRoutingUserIdRoute =
  ContentDynamicRoutingUserIdRouteImport.update({
    id: '/content/dynamic-routing/$userId',
    path: '/content/dynamic-routing/$userId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ContentLayoutRoutesIndexRoute =
  ContentLayoutRoutesIndexRouteImport.update({
    id: '/content/layout-routes/',
    path: '/content/layout-routes/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ContentNavigationIndexRoute = ContentNavigationIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ContentNavigationRouteRoute,
} as any)
const ContentNavigationLinkRoute = ContentNavigationLinkRouteImport.update({
  id: '/link',
  path: '/link',
  getParentRoute: () => ContentNavigationRouteRoute,
} as any)
const ContentNavigationUseNavigateRoute =
  ContentNavigationUseNavigateRouteImport.update({
    id: '/use-navigate',
    path: '/use-navigate',
    getParentRoute: () => ContentNavigationRouteRoute,
  } as any)
const ContentNestedRoutingIndexRoute =
  ContentNestedRoutingIndexRouteImport.update({
    id: '/content/nested-routing/',
    path: '/content/nested-routing/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ContentRoutingIndexRoute = ContentRoutingIndexRouteImport.update({
  id: '/content/routing/',
  path: '/content/routing/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/content/navigation': typeof ContentNavigationRouteRouteWithChildren
  '/content/': typeof ContentIndexRoute
  '/content/dynamic-routing/$userId': typeof ContentDynamicRoutingUserIdRoute
  '/content/navigation/link': typeof ContentNavigationLinkRoute
  '/content/navigation/use-navigate': typeof ContentNavigationUseNavigateRoute
  '/content/data-loaders/': typeof ContentDataLoadersIndexRoute
  '/content/dynamic-routing/': typeof ContentDynamicRoutingIndexRoute
  '/content/layout-routes/': typeof ContentLayoutRoutesIndexRoute
  '/content/navigation/': typeof ContentNavigationIndexRoute
  '/content/nested-routing/': typeof ContentNestedRoutingIndexRoute
  '/content/routing/': typeof ContentRoutingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/content': typeof ContentIndexRoute
  '/content/dynamic-routing/$userId': typeof ContentDynamicRoutingUserIdRoute
  '/content/navigation/link': typeof ContentNavigationLinkRoute
  '/content/navigation/use-navigate': typeof ContentNavigationUseNavigateRoute
  '/content/data-loaders': typeof ContentDataLoadersIndexRoute
  '/content/dynamic-routing': typeof ContentDynamicRoutingIndexRoute
  '/content/layout-routes': typeof ContentLayoutRoutesIndexRoute
  '/content/navigation': typeof ContentNavigationIndexRoute
  '/content/nested-routing': typeof ContentNestedRoutingIndexRoute
  '/content/routing': typeof ContentRoutingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/content/navigation': typeof ContentNavigationRouteRouteWithChildren
  '/content/': typeof ContentIndexRoute
  '/content/dynamic-routing/$userId': typeof ContentDynamicRoutingUserIdRoute
  '/content/navigation/link': typeof ContentNavigationLinkRoute
  '/content/navigation/use-navigate': typeof ContentNavigationUseNavigateRoute
  '/content/data-loaders/': typeof ContentDataLoadersIndexRoute
  '/content/dynamic-routing/': typeof ContentDynamicRoutingIndexRoute
  '/content/layout-routes/': typeof ContentLayoutRoutesIndexRoute
  '/content/navigation/': typeof ContentNavigationIndexRoute
  '/content/nested-routing/': typeof ContentNestedRoutingIndexRoute
  '/content/routing/': typeof ContentRoutingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/content/navigation'
    | '/content/'
    | '/content/dynamic-routing/$userId'
    | '/content/navigation/link'
    | '/content/navigation/use-navigate'
    | '/content/data-loaders/'
    | '/content/dynamic-routing/'
    | '/content/layout-routes/'
    | '/content/navigation/'
    | '/content/nested-routing/'
    | '/content/routing/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/content'
    | '/content/dynamic-routing/$userId'
    | '/content/navigation/link'
    | '/content/navigation/use-navigate'
    | '/content/data-loaders'
    | '/content/dynamic-routing'
    | '/content/layout-routes'
    | '/content/navigation'
    | '/content/nested-routing'
    | '/content/routing'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/content/navigation'
    | '/content/'
    | '/content/dynamic-routing/$userId'
    | '/content/navigation/link'
    | '/content/navigation/use-navigate'
    | '/content/data-loaders/'
    | '/content/dynamic-routing/'
    | '/content/layout-routes/'
    | '/content/navigation/'
    | '/content/nested-routing/'
    | '/content/routing/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContentNavigationRouteRoute: typeof ContentNavigationRouteRouteWithChildren
  ContentIndexRoute: typeof ContentIndexRoute
  ContentDynamicRoutingUserIdRoute: typeof ContentDynamicRoutingUserIdRoute
  ContentDataLoadersIndexRoute: typeof ContentDataLoadersIndexRoute
  ContentDynamicRoutingIndexRoute: typeof ContentDynamicRoutingIndexRoute
  ContentLayoutRoutesIndexRoute: typeof ContentLayoutRoutesIndexRoute
  ContentNestedRoutingIndexRoute: typeof ContentNestedRoutingIndexRoute
  ContentRoutingIndexRoute: typeof ContentRoutingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/': {
      id: '/content/'
      path: '/content'
      fullPath: '/content/'
      preLoaderRoute: typeof ContentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/navigation': {
      id: '/content/navigation'
      path: '/content/navigation'
      fullPath: '/content/navigation'
      preLoaderRoute: typeof ContentNavigationRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/data-loaders/': {
      id: '/content/data-loaders/'
      path: '/content/data-loaders'
      fullPath: '/content/data-loaders/'
      preLoaderRoute: typeof ContentDataLoadersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/dynamic-routing/': {
      id: '/content/dynamic-routing/'
      path: '/content/dynamic-routing'
      fullPath: '/content/dynamic-routing/'
      preLoaderRoute: typeof ContentDynamicRoutingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/dynamic-routing/$userId': {
      id: '/content/dynamic-routing/$userId'
      path: '/content/dynamic-routing/$userId'
      fullPath: '/content/dynamic-routing/$userId'
      preLoaderRoute: typeof ContentDynamicRoutingUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/layout-routes/': {
      id: '/content/layout-routes/'
      path: '/content/layout-routes'
      fullPath: '/content/layout-routes/'
      preLoaderRoute: typeof ContentLayoutRoutesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/navigation/': {
      id: '/content/navigation/'
      path: '/'
      fullPath: '/content/navigation/'
      preLoaderRoute: typeof ContentNavigationIndexRouteImport
      parentRoute: typeof ContentNavigationRouteRoute
    }
    '/content/navigation/link': {
      id: '/content/navigation/link'
      path: '/link'
      fullPath: '/content/navigation/link'
      preLoaderRoute: typeof ContentNavigationLinkRouteImport
      parentRoute: typeof ContentNavigationRouteRoute
    }
    '/content/navigation/use-navigate': {
      id: '/content/navigation/use-navigate'
      path: '/use-navigate'
      fullPath: '/content/navigation/use-navigate'
      preLoaderRoute: typeof ContentNavigationUseNavigateRouteImport
      parentRoute: typeof ContentNavigationRouteRoute
    }
    '/content/nested-routing/': {
      id: '/content/nested-routing/'
      path: '/content/nested-routing'
      fullPath: '/content/nested-routing/'
      preLoaderRoute: typeof ContentNestedRoutingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/routing/': {
      id: '/content/routing/'
      path: '/content/routing'
      fullPath: '/content/routing/'
      preLoaderRoute: typeof ContentRoutingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ContentNavigationRouteRouteChildren {
  ContentNavigationLinkRoute: typeof ContentNavigationLinkRoute
  ContentNavigationUseNavigateRoute: typeof ContentNavigationUseNavigateRoute
  ContentNavigationIndexRoute: typeof ContentNavigationIndexRoute
}

const ContentNavigationRouteRouteChildren: ContentNavigationRouteRouteChildren =
  {
    ContentNavigationLinkRoute: ContentNavigationLinkRoute,
    ContentNavigationUseNavigateRoute: ContentNavigationUseNavigateRoute,
    ContentNavigationIndexRoute: ContentNavigationIndexRoute,
  }

const ContentNavigationRouteRouteWithChildren =
  ContentNavigationRouteRoute._addFileChildren(
    ContentNavigationRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContentNavigationRouteRoute: ContentNavigationRouteRouteWithChildren,
  ContentIndexRoute: ContentIndexRoute,
  ContentDynamicRoutingUserIdRoute: ContentDynamicRoutingUserIdRoute,
  ContentDataLoadersIndexRoute: ContentDataLoadersIndexRoute,
  ContentDynamicRoutingIndexRoute: ContentDynamicRoutingIndexRoute,
  ContentLayoutRoutesIndexRoute: ContentLayoutRoutesIndexRoute,
  ContentNestedRoutingIndexRoute: ContentNestedRoutingIndexRoute,
  ContentRoutingIndexRoute: ContentRoutingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
